import { Inter, Poppins, Lato } from "@next/font/google";

import "./globals.css";
import Footer from "./components/footer";
import Navbar from "./components/navbar-homepage";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
